
CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Loading pytorch-gpu/py3/1.12.1
  Loading requirement: cuda/11.2 nccl/2.9.6-1-cuda cudnn/8.1.1.33-cuda gcc/8.5.0
    openmpi/4.1.1-cuda intel-mkl/2020.4 magma/2.5.4-cuda-oneapi-mkl sox/14.4.2
    sparsehash/2.0.3 libjpeg-turbo/2.1.3
+ srun python -m src.evaluate --experiment-name jz_first_test --dataset kill --model google/flan-t5-small --question-types ab --eval-nb-samples 1 --dataset-folder paperlaws
Traceback (most recent call last):
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/pytorch-gpu-1.12.1+py3.10.4/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/gpfslocalsup/pub/anaconda-py3/2022.05/envs/pytorch-gpu-1.12.1+py3.10.4/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/lustre/fswork/projects/rech/aho/uus79sn/llm_alignment/src/evaluate.py", line 8, in <module>
    from src.models import (
  File "/lustre/fswork/projects/rech/aho/uus79sn/llm_alignment/src/models.py", line 6, in <module>
    import ai21
ModuleNotFoundError: No module named 'ai21'
srun: error: r10i0n3: task 0: Exited with exit code 1
srun: Terminating StepId=1055505.0
